import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import theme from "@/theme/theme";
import { ThemeProvider } from "@mui/material";
import Hero from "@/components/hero/Hero";
import dynamic from "next/dynamic";
// import NavBar from "@/components/navbar/Navbar";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const NoSSRero = dynamic(() => import("@/components/hero/Hero"), {
  ssr: false,
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="cz">
      <ThemeProvider theme={theme}>
        <NoSSRero />
        <body className={inter.className}>{children}</body>
      </ThemeProvider>
    </html>
  );
}
