import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./styling/globals.css";
import theme from "@/theme/theme";
import { ThemeProvider } from "@mui/material";
import dynamic from "next/dynamic";
import Footer from "@/components/footer/Footer";
// import NavBar from "@/components/navbar/Navbar";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const NoSSRHero = dynamic(() => import("@/components/hero/Hero"), {
  ssr: false,
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="cz">
      <body className={inter.className}>
        <ThemeProvider theme={theme}>
          <NoSSRHero />
          <main className="min-h-screen">
          {children}

          </main>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
